<!-- aroma-admin/src/components/product/StepBasicInfo.vue -->
<template>
  <div class="space-y-4">
    <!-- Names + slug -->
    <section class="bg-dash-surface rounded-card shadow-card p-5">
      <h2 class="text-xs font-semibold text-dash-text mb-4">{{ t('productCreate.basicInfo') }}</h2>
      <div class="space-y-3">
        <div class="grid grid-cols-2 gap-3">
          <div>
            <AInput
              v-model="form.name"
              :label="t('productCreate.arabicName')"
              :error="errors.name"
              dir="rtl"
              placeholder="أدخل اسم المنتج"
            />
            <p class="mt-1.5 text-2xs text-dash-muted">{{ t('productCreate.arabicNameHint') }}</p>
          </div>
          <div>
            <AInput
              v-model="form.name_en"
              :label="t('productCreate.englishName')"
              placeholder="e.g. Oud Royale"
              @input="syncSlug"
            />
            <p class="mt-1.5 text-2xs text-dash-muted">{{ t('productCreate.englishNameHint') }}</p>
          </div>
        </div>
        <!-- Slug preview -->
        <div
          v-if="form.slug"
          class="flex items-center gap-2 rounded-btn bg-dash-bg border border-dash-border px-3 py-2"
        >
          <Link2 :size="12" class="text-dash-faint shrink-0" />
          <span class="text-2xs text-dash-muted">aromashop.ly/products/</span>
          <span class="text-2xs font-medium text-dash-text font-mono">{{ form.slug }}</span>
          <span class="ml-auto text-2xs text-dash-faint">{{ t('productCreate.slugAutoGenerated') }}</span>
        </div>
        <div
          v-else
          class="flex items-center gap-2 rounded-btn bg-dash-bg border border-dashed border-dash-border px-3 py-2"
        >
          <Link2 :size="12" class="text-dash-faint shrink-0" />
          <span class="text-2xs text-dash-faint">{{ t('productCreate.slugHint') }}</span>
        </div>
      </div>
    </section>

    <!-- Description -->
    <section class="bg-dash-surface rounded-card shadow-card p-5">
      <h2 class="text-xs font-semibold text-dash-text mb-4">{{ t('productCreate.description') }}</h2>
      <ATextarea v-model="form.description" :placeholder="t('productCreate.descriptionHint')" rows="4" />
    </section>

    <!-- Two-column sidebar layout -->
    <div class="grid grid-cols-1 lg:grid-cols-[1fr_272px] gap-4">
      <div class="space-y-4">
        <!-- Status flags -->
        <section class="bg-dash-surface rounded-card shadow-card p-5">
          <h2 class="text-xs font-semibold text-dash-text mb-3">{{ t('productCreate.status') }}</h2>
          <div class="space-y-1">
            <label
              v-for="flag in flags"
              :key="flag.key"
              class="flex items-center gap-3 px-3 py-2.5 rounded-btn cursor-pointer
                     hover:bg-dash-bg transition-colors duration-150 group"
            >
              <div
                class="w-4 h-4 rounded border-[1.5px] flex items-center justify-center shrink-0 transition-all duration-150"
                :class="form[flag.key]
                  ? 'bg-dash-secondary border-dash-secondary'
                  : 'border-dash-border group-hover:border-dash-muted'"
              >
                <Check v-if="form[flag.key]" :size="10" class="text-white" stroke-width="2.5" />
              </div>
              <input type="checkbox" v-model="form[flag.key]" class="sr-only" />
              <div>
                <p class="text-xs font-medium text-dash-text">{{ t(flag.labelKey) }}</p>
                <p class="text-2xs text-dash-muted">{{ t(flag.hintKey) }}</p>
              </div>
            </label>
          </div>
        </section>
      </div>

      <div class="space-y-4">
        <!-- Organize -->
        <section class="bg-dash-surface rounded-card shadow-card p-5">
          <h2 class="text-xs font-semibold text-dash-text mb-4">{{ t('productCreate.organize') }}</h2>
          <div class="space-y-3">
            <ASelect v-model="form.brand_id"    :label="t('productCreate.brandLabel')"    :options="brandOptions"    :placeholder="t('productCreate.chooseBrand')"    :error="errors.brand_id" />
            <ASelect v-model="form.category_id" :label="t('productCreate.categoryLabel')" :options="categoryOptions" :placeholder="t('productCreate.chooseCategory')" :error="errors.category_id" />
            <ASelect v-model="form.type"         :label="t('products.typeLabel')"           :options="typeOptions"     :placeholder="t('productCreate.chooseType')"     :error="errors.type" />
          </div>
        </section>

        <!-- Card color -->
        <section class="bg-dash-surface rounded-card shadow-card p-5">
          <h2 class="text-xs font-semibold text-dash-text mb-4">{{ t('productCreate.cardColor') }}</h2>
          <div class="space-y-3">
            <div>
              <p class="text-2xs text-dash-muted mb-1.5">{{ t('productCreate.colorBackground') }}</p>
              <div class="flex items-center gap-2">
                <div class="relative w-8 h-8 rounded-btn overflow-hidden border border-dash-border shrink-0">
                  <input type="color" v-model="form.placeholder_bg" class="absolute inset-0 w-full h-full cursor-pointer opacity-0" />
                  <div class="w-full h-full" :style="{ backgroundColor: form.placeholder_bg }" />
                </div>
                <input type="text" v-model="form.placeholder_bg" maxlength="7"
                  class="flex-1 min-w-0 rounded-btn border border-dash-border bg-dash-bg px-2.5 py-1.5
                         text-xs font-mono text-dash-text focus:outline-none focus:border-dash-primary" />
              </div>
            </div>
            <div>
              <p class="text-2xs text-dash-muted mb-1.5">{{ t('productCreate.colorAccent') }}</p>
              <div class="flex items-center gap-2">
                <div class="relative w-8 h-8 rounded-btn overflow-hidden border border-dash-border shrink-0">
                  <input type="color" v-model="form.placeholder_dot" class="absolute inset-0 w-full h-full cursor-pointer opacity-0" />
                  <div class="w-full h-full" :style="{ backgroundColor: form.placeholder_dot }" />
                </div>
                <input type="text" v-model="form.placeholder_dot" maxlength="7"
                  class="flex-1 min-w-0 rounded-btn border border-dash-border bg-dash-bg px-2.5 py-1.5
                         text-xs font-mono text-dash-text focus:outline-none focus:border-dash-primary" />
              </div>
            </div>
            <div class="rounded-btn h-10 flex items-center justify-center gap-2"
                 :style="{ backgroundColor: form.placeholder_bg }">
              <div class="w-3 h-3 rounded-full" :style="{ backgroundColor: form.placeholder_dot }" />
              <span class="text-2xs font-medium" :style="{ color: form.placeholder_dot }">{{ t('productCreate.colorPreview') }}</span>
            </div>
          </div>
        </section>
      </div>
    </div>

    <!-- Error summary -->
    <div v-if="errors.general" class="rounded-card border border-dash-danger/20 bg-dash-danger-lt px-4 py-3 flex items-start gap-2">
      <AlertCircle :size="14" class="text-dash-danger shrink-0 mt-0.5" />
      <p class="text-xs text-dash-danger">{{ errors.general }}</p>
    </div>

    <!-- Nav -->
    <div class="flex justify-end pt-2">
      <AButton size="sm" :loading="saving" @click="handleNext">
        {{ t('stepper.nextImages') }}
      </AButton>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useI18n } from 'vue-i18n'
import { Link2, Check, AlertCircle } from 'lucide-vue-next'
import { apiGetBrands, apiGetCategories, apiCreateProduct, apiUpdateProduct } from '../../api/admin'
import type { AdminBrand, AdminCategory, AdminProduct } from '../../types'
import AInput    from '../ui/AInput.vue'
import ATextarea from '../ui/ATextarea.vue'
import ASelect   from '../ui/ASelect.vue'
import AButton   from '../ui/AButton.vue'

const props = defineProps<{
  productId: number | null
  initialData?: AdminProduct | null
}>()

const emit = defineEmits<{
  saved: [productId: number]
}>()

const { t } = useI18n()

const brands = ref<AdminBrand[]>([])
const cats   = ref<AdminCategory[]>([])
const saving = ref(false)
const errors = ref<Record<string, string>>({})

const typeOptions     = ['EDP', 'EDT', 'Parfum', 'EDC'].map(v => ({ value: v, label: v }))
const brandOptions    = computed(() => brands.value.map(b => ({ value: String(b.id), label: b.name })))
const categoryOptions = computed(() => cats.value.map(c => ({ value: String(c.id), label: c.label })))

const flags = [
  { key: 'is_new'        as const, labelKey: 'productCreate.newArrivalLabel', hintKey: 'productCreate.newArrivalHint' },
  { key: 'is_bestseller' as const, labelKey: 'productCreate.bestsellerLabel', hintKey: 'productCreate.bestsellerHint' },
  { key: 'is_offer'      as const, labelKey: 'productCreate.onOfferLabel',    hintKey: 'productCreate.onOfferHint' },
]

const emptyForm = () => ({
  name:            '',
  name_en:         '',
  slug:            '',
  brand_id:        '',
  category_id:     '',
  type:            '',
  description:     '',
  is_new:          false as boolean,
  is_bestseller:   false as boolean,
  is_offer:        false as boolean,
  placeholder_bg:  '#F2E8E5',
  placeholder_dot: '#C9A0A0',
})

const form = ref(emptyForm())

function toSlug(s: string): string {
  return s.toLowerCase().trim()
    .replace(/[^\w\s-]/g, '')
    .replace(/[\s_]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
}

function syncSlug() {
  form.value.slug = toSlug(form.value.name_en)
}

async function handleNext() {
  errors.value = {}
  if (!form.value.name)        { errors.value.name        = t('productCreate.arabicNameRequired');    return }
  if (!form.value.slug)        { errors.value.name_en     = t('productCreate.englishNameRequired');   return }
  if (!form.value.brand_id)    { errors.value.brand_id    = t('productCreate.selectBrandRequired');   return }
  if (!form.value.category_id) { errors.value.category_id = t('productCreate.selectCategoryRequired'); return }
  if (!form.value.type)        { errors.value.type        = t('productCreate.selectTypeRequired');     return }

  saving.value = true
  try {
    const payload = {
      name:            form.value.name,
      name_en:         form.value.name_en     || undefined,
      slug:            form.value.slug,
      brand_id:        form.value.brand_id,
      category_id:     form.value.category_id,
      type:            form.value.type,
      description:     form.value.description || undefined,
      placeholder_bg:  form.value.placeholder_bg,
      placeholder_dot: form.value.placeholder_dot,
      is_new:          form.value.is_new,
      is_bestseller:   form.value.is_bestseller,
      is_offer:        form.value.is_offer,
    }
    if (props.productId) {
      await apiUpdateProduct(props.productId, payload)
      emit('saved', props.productId)
    } else {
      const { data } = await apiCreateProduct(payload)
      emit('saved', data.id)
    }
  } catch (e: unknown) {
    errors.value.general = (e as any)?.response?.data?.message ?? t('common.saveFailed')
  } finally {
    saving.value = false
  }
}

onMounted(async () => {
  try {
    const [b, c] = await Promise.all([apiGetBrands(), apiGetCategories()])
    brands.value = b.data
    cats.value   = c.data
  } catch { /* dropdowns stay empty */ }

  if (props.initialData) {
    const p = props.initialData
    form.value = {
      name:            p.name,
      name_en:         p.nameEn ?? '',
      slug:            p.slug,
      brand_id:        p.brandId,
      category_id:     p.categoryId,
      type:            p.type,
      description:     p.description ?? '',
      is_new:          p.isNew,
      is_bestseller:   p.isBestseller,
      is_offer:        p.isOffer,
      placeholder_bg:  p.placeholderBg  || '#F2E8E5',
      placeholder_dot: p.placeholderDot || '#C9A0A0',
    }
  }
})
</script>
