<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'slug'            => 'sauvage',
                'brand_id'        => 'dior',
                'category_id'     => 2,
                'name'            => 'سوفاج',
                'name_en'         => 'Sauvage',
                'description'     => 'مستوحى من الفضاءات المفتوحة تحت سماء الليل. سوفاج من ديور عطر يجمع بين النقاء الجامح والعمق الخشبي في توازن لا مثيل له.',
                'type'            => 'EDP',
                'rating'          => 4.9,
                'reviews_count'   => 342,
                'is_new'          => false,
                'is_bestseller'   => true,
                'is_offer'        => false,
                'placeholder_bg'  => '#D8E0E8',
                'placeholder_dot' => '#5070A0',
                'variants' => [
                    ['size' => '60ml',  'price' => 480.00, 'original_price' => null,   'stock' => 'in_stock'],
                    ['size' => '100ml', 'price' => 480.00, 'original_price' => null,   'stock' => 'in_stock'],
                    ['size' => '200ml', 'price' => 480.00, 'original_price' => null,   'stock' => 'in_stock'],
                ],
                'notes' => [
                    ['type' => 'top',   'note' => 'فلفل كالابريا'],
                    ['type' => 'top',   'note' => 'برغموت'],
                    ['type' => 'heart', 'note' => 'فيتيفر'],
                    ['type' => 'heart', 'note' => 'لافندر'],
                    ['type' => 'heart', 'note' => 'جيرانيوم'],
                    ['type' => 'base',  'note' => 'أميبروكسان'],
                    ['type' => 'base',  'note' => 'صندل'],
                ],
                'tags' => ['طازج', 'خشبي', 'جريء'],
            ],
            [
                'slug'            => 'miss-dior',
                'brand_id'        => 'dior',
                'category_id'     => 1,
                'name'            => 'ميس ديور',
                'name_en'         => 'Miss Dior',
                'description'     => 'قصيدة في أجمل الأزهار. ميس ديور تنفتح بالفلفل الوردي المنعش ثم تتكشف عن قلب ورود دمشقية فاخرة — عطر يليق بكل امرأة شاء لها القدر أن تكون استثنائية.',
                'type'            => 'EDP',
                'rating'          => 4.8,
                'reviews_count'   => 218,
                'is_new'          => true,
                'is_bestseller'   => false,
                'is_offer'        => true,
                'placeholder_bg'  => '#F2E8E5',
                'placeholder_dot' => '#C9A0A0',
                'variants' => [
                    ['size' => '30ml',  'price' => 420.00, 'original_price' => 510.00, 'stock' => 'in_stock'],
                    ['size' => '50ml',  'price' => 420.00, 'original_price' => 510.00, 'stock' => 'in_stock'],
                    ['size' => '100ml', 'price' => 420.00, 'original_price' => 510.00, 'stock' => 'in_stock'],
                ],
                'notes' => [
                    ['type' => 'top',   'note' => 'فلفل وردي'],
                    ['type' => 'top',   'note' => 'برغموت'],
                    ['type' => 'heart', 'note' => 'وردة دمشقية'],
                    ['type' => 'heart', 'note' => 'ياسمين غراس'],
                    ['type' => 'base',  'note' => 'باتشولي'],
                    ['type' => 'base',  'note' => 'مسك أبيض'],
                ],
                'tags' => ['زهري', 'رومانسي', 'راقٍ'],
            ],
            [
                'slug'            => 'bleu-de-chanel',
                'brand_id'        => 'chanel',
                'category_id'     => 2,
                'name'            => 'بلو دو شانيل',
                'name_en'         => 'Bleu de Chanel',
                'description'     => 'حرية المعاصرة. بلو دو شانيل يعبّر عن الرجل الذي يتجاوز حدود التوقعات — رائحة خشبية طازجة تعكس روحاً لا تعرف القيود.',
                'type'            => 'EDP',
                'rating'          => 4.9,
                'reviews_count'   => 405,
                'is_new'          => false,
                'is_bestseller'   => true,
                'is_offer'        => false,
                'placeholder_bg'  => '#E0E8F0',
                'placeholder_dot' => '#6080A8',
                'variants' => [
                    ['size' => '50ml',  'price' => 445.00, 'original_price' => null, 'stock' => 'in_stock'],
                    ['size' => '100ml', 'price' => 445.00, 'original_price' => null, 'stock' => 'in_stock'],
                    ['size' => '150ml', 'price' => 445.00, 'original_price' => null, 'stock' => 'in_stock'],
                ],
                'notes' => [
                    ['type' => 'top',   'note' => 'ليمون'],
                    ['type' => 'top',   'note' => 'نعناع'],
                    ['type' => 'top',   'note' => 'فلفل وردي'],
                    ['type' => 'heart', 'note' => 'زنجبيل'],
                    ['type' => 'heart', 'note' => 'جيرانيوم'],
                    ['type' => 'heart', 'note' => 'نيرولي'],
                    ['type' => 'base',  'note' => 'صندل'],
                    ['type' => 'base',  'note' => 'خشب أرز'],
                    ['type' => 'base',  'note' => 'لبان'],
                ],
                'tags' => ['خشبي', 'حار', 'كلاسيكي'],
            ],
            [
                'slug'            => 'oud-wood',
                'brand_id'        => 'tom-ford',
                'category_id'     => 3,
                'name'            => 'عود وود',
                'name_en'         => 'Oud Wood',
                'description'     => 'توم فورد يعيد تعريف العود لجيل جديد. عود وود تركيبة نادرة تجمع بين الأخشاب الشرقية والغربية في توازن مذهل — رائحة تترك أثراً لا يُمحى.',
                'type'            => 'EDP',
                'rating'          => 4.8,
                'reviews_count'   => 176,
                'is_new'          => false,
                'is_bestseller'   => false,
                'is_offer'        => false,
                'placeholder_bg'  => '#E8DDD0',
                'placeholder_dot' => '#9A7050',
                'variants' => [
                    ['size' => '50ml',  'price' => 650.00, 'original_price' => null, 'stock' => 'in_stock'],
                    ['size' => '100ml', 'price' => 650.00, 'original_price' => null, 'stock' => 'in_stock'],
                    ['size' => '250ml', 'price' => 650.00, 'original_price' => null, 'stock' => 'in_stock'],
                ],
                'notes' => [
                    ['type' => 'top',   'note' => 'عود نادر'],
                    ['type' => 'top',   'note' => 'خشب ورد'],
                    ['type' => 'heart', 'note' => 'صندل'],
                    ['type' => 'heart', 'note' => 'فتيفر'],
                    ['type' => 'base',  'note' => 'أمبر'],
                    ['type' => 'base',  'note' => 'مسك'],
                ],
                'tags' => ['عود', 'خشبي', 'فاخر'],
            ],
            [
                'slug'            => 'black-orchid',
                'brand_id'        => 'tom-ford',
                'category_id'     => 1,
                'name'            => 'بلاك أوركيد',
                'name_en'         => 'Black Orchid',
                'description'     => 'رمز الفخامة الداكنة. بلاك أوركيد من توم فورد تحفة حسية نادرة — وردة الأوركيد السوداء تلتقي بالخشب الغامق في إغراء لا تقاومه.',
                'type'            => 'EDP',
                'rating'          => 4.9,
                'reviews_count'   => 134,
                'is_new'          => false,
                'is_bestseller'   => true,
                'is_offer'        => false,
                'placeholder_bg'  => '#2E2830',
                'placeholder_dot' => '#B080C0',
                'variants' => [
                    ['size' => '30ml',  'price' => 590.00, 'original_price' => null, 'stock' => 'in_stock'],
                    ['size' => '50ml',  'price' => 590.00, 'original_price' => null, 'stock' => 'in_stock'],
                    ['size' => '100ml', 'price' => 590.00, 'original_price' => null, 'stock' => 'in_stock'],
                ],
                'notes' => [
                    ['type' => 'top',   'note' => 'كافيار'],
                    ['type' => 'top',   'note' => 'إيلانج إيلانج'],
                    ['type' => 'heart', 'note' => 'أوركيد سوداء'],
                    ['type' => 'heart', 'note' => 'لوتس'],
                    ['type' => 'base',  'note' => 'باتشولي'],
                    ['type' => 'base',  'note' => 'صندل'],
                    ['type' => 'base',  'note' => 'فيتيفر'],
                ],
                'tags' => ['فاخر', 'غامض', 'حسّي'],
            ],
            [
                'slug'            => 'aventus',
                'brand_id'        => 'creed',
                'category_id'     => 2,
                'name'            => 'أفنتوس',
                'name_en'         => 'Aventus',
                'description'     => 'الأسطورة الحية. أفنتوس من كريد مستوحى من مسيرة نابليون — رائحة تصنع الأسطورة وتليق بكل من خُلق ليفرض نفسه.',
                'type'            => 'EDP',
                'rating'          => 5.0,
                'reviews_count'   => 89,
                'is_new'          => false,
                'is_bestseller'   => true,
                'is_offer'        => false,
                'placeholder_bg'  => '#EDE0C8',
                'placeholder_dot' => '#B8906A',
                'variants' => [
                    ['size' => '50ml',  'price' => 780.00, 'original_price' => null, 'stock' => 'low_stock'],
                    ['size' => '100ml', 'price' => 780.00, 'original_price' => null, 'stock' => 'low_stock'],
                    ['size' => '250ml', 'price' => 780.00, 'original_price' => null, 'stock' => 'low_stock'],
                ],
                'notes' => [
                    ['type' => 'top',   'note' => 'أناناس'],
                    ['type' => 'top',   'note' => 'برغموت'],
                    ['type' => 'top',   'note' => 'تفاح أخضر'],
                    ['type' => 'heart', 'note' => 'بتولا'],
                    ['type' => 'heart', 'note' => 'باتشولي'],
                    ['type' => 'heart', 'note' => 'ياسمين'],
                    ['type' => 'base',  'note' => 'مسك'],
                    ['type' => 'base',  'note' => 'عنبر'],
                    ['type' => 'base',  'note' => 'صندل'],
                ],
                'tags' => ['فاكهي', 'خشبي', 'ملكي'],
            ],
            [
                'slug'            => 'layton',
                'brand_id'        => 'parfums-de-marly',
                'category_id'     => 2,
                'name'            => 'ليتون',
                'name_en'         => 'Layton',
                'description'     => 'ليتون من بارفومز دو مارلي دفء ملكي في كل رشّة — مزيج من التفاح الحلو واللافندر المنعش يتلاشى في قاعدة خشبية ناعمة.',
                'type'            => 'EDP',
                'rating'          => 4.8,
                'reviews_count'   => 203,
                'is_new'          => false,
                'is_bestseller'   => true,
                'is_offer'        => false,
                'placeholder_bg'  => '#EDE8F2',
                'placeholder_dot' => '#8878B0',
                'variants' => [
                    ['size' => '75ml',  'price' => 520.00, 'original_price' => null, 'stock' => 'in_stock'],
                    ['size' => '125ml', 'price' => 520.00, 'original_price' => null, 'stock' => 'in_stock'],
                ],
                'notes' => [
                    ['type' => 'top',   'note' => 'تفاح'],
                    ['type' => 'top',   'note' => 'لافندر'],
                    ['type' => 'top',   'note' => 'برغموت'],
                    ['type' => 'heart', 'note' => 'ياسمين'],
                    ['type' => 'heart', 'note' => 'فانيليا'],
                    ['type' => 'heart', 'note' => 'جيرانيوم'],
                    ['type' => 'base',  'note' => 'صندل'],
                    ['type' => 'base',  'note' => 'مسك'],
                    ['type' => 'base',  'note' => 'خشب الكشمير'],
                ],
                'tags' => ['ناعم', 'حلو', 'إطاري'],
            ],
            [
                'slug'            => 'delina',
                'brand_id'        => 'parfums-de-marly',
                'category_id'     => 1,
                'name'            => 'ديلينا',
                'name_en'         => 'Delina',
                'description'     => 'ديلينا سحر بارفومز دو مارلي الأنثوي الخالص — توبروز حالم وورد تركي فاخر يتصاعد من قاعدة دافئة بالفانيليا، يليق بكل امرأة تريد أن تترك أثراً.',
                'type'            => 'EDP',
                'rating'          => 4.9,
                'reviews_count'   => 157,
                'is_new'          => true,
                'is_bestseller'   => false,
                'is_offer'        => true,
                'placeholder_bg'  => '#F2E0EC',
                'placeholder_dot' => '#C080A0',
                'variants' => [
                    ['size' => '75ml',  'price' => 560.00, 'original_price' => 650.00, 'stock' => 'in_stock'],
                    ['size' => '125ml', 'price' => 560.00, 'original_price' => 650.00, 'stock' => 'in_stock'],
                ],
                'notes' => [
                    ['type' => 'top',   'note' => 'راوند'],
                    ['type' => 'top',   'note' => 'كمثرى'],
                    ['type' => 'heart', 'note' => 'توبروز'],
                    ['type' => 'heart', 'note' => 'وردة تركية'],
                    ['type' => 'heart', 'note' => 'قرنفل'],
                    ['type' => 'base',  'note' => 'فانيليا'],
                    ['type' => 'base',  'note' => 'مسك'],
                    ['type' => 'base',  'note' => 'خشب الكشمير'],
                ],
                'tags' => ['زهري', 'رومانسي', 'مسائي'],
            ],
            [
                'slug'            => 'interlude-man',
                'brand_id'        => 'amouage',
                'category_id'     => 2,
                'name'            => 'إنترلود مان',
                'name_en'         => 'Interlude Man',
                'description'     => 'رحلة في الزمن. إنترلود مان من عمواج يروي قصة الرجل الذي شهد الحضارات تتعاقب — عطر عميق ومعقد يستحق التأمل.',
                'type'            => 'EDP',
                'rating'          => 4.9,
                'reviews_count'   => 67,
                'is_new'          => false,
                'is_bestseller'   => false,
                'is_offer'        => false,
                'placeholder_bg'  => '#DDE8EC',
                'placeholder_dot' => '#507090',
                'variants' => [
                    ['size' => '50ml',  'price' => 620.00, 'original_price' => null, 'stock' => 'in_stock'],
                    ['size' => '100ml', 'price' => 620.00, 'original_price' => null, 'stock' => 'in_stock'],
                ],
                'notes' => [
                    ['type' => 'top',   'note' => 'بخور'],
                    ['type' => 'top',   'note' => 'إيليمي'],
                    ['type' => 'top',   'note' => 'برغموت'],
                    ['type' => 'heart', 'note' => 'أوريس'],
                    ['type' => 'heart', 'note' => 'مر'],
                    ['type' => 'heart', 'note' => 'راتنج'],
                    ['type' => 'base',  'note' => 'عود'],
                    ['type' => 'base',  'note' => 'لبان'],
                    ['type' => 'base',  'note' => 'صندل'],
                ],
                'tags' => ['شرقي', 'راتنجي', 'عميق'],
            ],
            [
                'slug'            => 'reflection-man',
                'brand_id'        => 'amouage',
                'category_id'     => 2,
                'name'            => 'ريفلكشن مان',
                'name_en'         => 'Reflection Man',
                'description'     => 'ريفلكشن مان من عمواج نقاء مطلق — عطر أبيض وهادئ يشبه الماء النقي على الجلد، بعمق الأوريس وخفة الليمون.',
                'type'            => 'EDP',
                'rating'          => 4.7,
                'reviews_count'   => 94,
                'is_new'          => true,
                'is_bestseller'   => false,
                'is_offer'        => true,
                'placeholder_bg'  => '#E8ECF0',
                'placeholder_dot' => '#809090',
                'variants' => [
                    ['size' => '50ml',  'price' => 580.00, 'original_price' => 690.00, 'stock' => 'in_stock'],
                    ['size' => '100ml', 'price' => 580.00, 'original_price' => 690.00, 'stock' => 'in_stock'],
                ],
                'notes' => [
                    ['type' => 'top',   'note' => 'ليمون'],
                    ['type' => 'top',   'note' => 'روزماري'],
                    ['type' => 'heart', 'note' => 'إيريس'],
                    ['type' => 'heart', 'note' => 'ياسمين'],
                    ['type' => 'base',  'note' => 'صندل'],
                    ['type' => 'base',  'note' => 'مسك أبيض'],
                ],
                'tags' => ['نظيف', 'ناعم', 'فاخر'],
            ],
            [
                'slug'            => 'oud-for-glory',
                'brand_id'        => 'lattafa',
                'category_id'     => 3,
                'name'            => 'عود للمجد',
                'name_en'         => 'Oud for Glory',
                'description'     => 'المجد في كل رشّة. عود للمجد من لطافة يقدم عطر العود الشرقي الملكي بجودة استثنائية وسعر في متناول الجميع — الفخامة لا تحتاج إلى ثمن خيالي.',
                'type'            => 'EDP',
                'rating'          => 4.7,
                'reviews_count'   => 312,
                'is_new'          => false,
                'is_bestseller'   => true,
                'is_offer'        => false,
                'placeholder_bg'  => '#EAE0D0',
                'placeholder_dot' => '#A07850',
                'variants' => [
                    ['size' => '100ml', 'price' => 145.00, 'original_price' => null, 'stock' => 'in_stock'],
                ],
                'notes' => [
                    ['type' => 'top',   'note' => 'زعفران'],
                    ['type' => 'top',   'note' => 'وردة'],
                    ['type' => 'heart', 'note' => 'عود كمبودي'],
                    ['type' => 'heart', 'note' => 'صندل'],
                    ['type' => 'base',  'note' => 'مسك'],
                    ['type' => 'base',  'note' => 'عنبر'],
                    ['type' => 'base',  'note' => 'لبان'],
                ],
                'tags' => ['عود', 'شرقي', 'قوي'],
            ],
            [
                'slug'            => 'amber-oud-gold',
                'brand_id'        => 'al-haramain',
                'category_id'     => 3,
                'name'            => 'أمبر عود ذهبي',
                'name_en'         => 'Amber Oud Gold',
                'description'     => 'الذهب السائل في زجاجة. أمبر عود ذهبي من الحرمين يجمع بين العنبر الدافئ والعود الشرقي النادر — رائحة تُذكّرك بليالي الخليج الساحرة.',
                'type'            => 'EDP',
                'rating'          => 4.6,
                'reviews_count'   => 278,
                'is_new'          => false,
                'is_bestseller'   => false,
                'is_offer'        => true,
                'placeholder_bg'  => '#F0E8D0',
                'placeholder_dot' => '#C0A050',
                'variants' => [
                    ['size' => '60ml',  'price' => 195.00, 'original_price' => 230.00, 'stock' => 'in_stock'],
                    ['size' => '100ml', 'price' => 195.00, 'original_price' => 230.00, 'stock' => 'in_stock'],
                ],
                'notes' => [
                    ['type' => 'top',   'note' => 'زعفران'],
                    ['type' => 'top',   'note' => 'عود'],
                    ['type' => 'heart', 'note' => 'ورد'],
                    ['type' => 'heart', 'note' => 'عنبر'],
                    ['type' => 'base',  'note' => 'مسك'],
                    ['type' => 'base',  'note' => 'فانيليا'],
                    ['type' => 'base',  'note' => 'صندل'],
                ],
                'tags' => ['شرقي', 'دافئ', 'ذهبي'],
            ],
        ];

        foreach ($products as $product) {
            $variants = $product['variants'];
            $notes    = $product['notes'];
            $tags     = $product['tags'];
            unset($product['variants'], $product['notes'], $product['tags']);

            $productId = DB::table('products')->insertGetId($product);

            foreach ($variants as $index => $variant) {
                $variant['product_id'] = $productId;
                $variant['is_default'] = $index === 0 ? 1 : 0;
                DB::table('product_variants')->insert($variant);
            }

            foreach ($notes as $note) {
                $note['product_id'] = $productId;
                DB::table('product_notes')->insert($note);
            }

            foreach ($tags as $tag) {
                DB::table('product_tags')->insert(['product_id' => $productId, 'tag' => $tag]);
            }
        }
    }
}
